CREATE TABLE Student (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    Registration NVARCHAR(20) NOT NULL UNIQUE,
    Course NVARCHAR(100),
    Status INT NOT NULL CHECK (Status IN (0, 1)) 
);