CREATE TABLE Loan (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    StudentId UNIQUEIDENTIFIER NOT NULL,
    BookId UNIQUEIDENTIFIER NOT NULL,
    LoanDate DATETIME NOT NULL DEFAULT GETDATE(),
    ExpectedReturnLoan DATETIME NOT NULL,
    ReturnLoan DATETIME NULL,
    Status INT NOT NULL CHECK (Status IN (0, 1, 2)) 

    CONSTRAINT FK_Emprestimo_Aluno FOREIGN KEY (StudentId) REFERENCES Student(Id),
    CONSTRAINT FK_Emprestimo_Livro FOREIGN KEY (BookId) REFERENCES Book(Id)
);